services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      environment:
        - DSN=${DSN}
        - SECRET_KEY=${SECRET_KEY}
        - GIN_MODE=release

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ridhotamma
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=libraryapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


