services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - DSN=${DSN}
        - SECRET_KEY=${SECRET_KEY}
        - GIN_MODE=release
    command: ["./wait-for-db.sh", "db:5432", "--", "./your-app-binary"]

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ridhotamma
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=libraryapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ridhotamma -d libraryapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:


